group_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.conf.urls.static import static
from django.conf import settings


class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/movies/user/' + user.username + '/profile_registration/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'group_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('movies.urls')),
    url(r'^movies/', include('movies.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.conf.urls import patterns, url
from movies import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^genre/(?P<genre_name_slug>[\w\-]+)/$', views.genre, name='genre'),
                       url(r'^movie/(?P<movie_name_slug>[\w\-]+)/$', views.movie, name='movie'),
                       url(r'^actor/(?P<actor_name_slug>[\w\-]+)/$', views.actor, name='actor'),
                       url(r'^genres/$', views.genres, name='genres'),
                       url(r'^actors/$', views.actors, name='actors'),
                       url(r'^add_movie/$', views.add_movie, name='add_movie'),
                       url(r'^user/(?P<username>[\w\-]+)/profile_registration/$', views.user_profile_registration, name='user_profile_details'),
                       url(r'^user/(?P<username>[\w\-]+)/edit_profile/$', views.edit_profile, name='edit_profile'),
                       url(r'^(?P<movie_slug>[\w\-]+)/add_character/$', views.add_character, name='add_character'),
                       url(r'^(?P<movie_slug>[\w\-]+)/add_actor/$', views.add_actor, name='add_actor'),
                       url(r'^(?P<movie_slug>[\w\-]+)/edit_movie/$', views.edit_movie, name='edit_movie'),
                       url(r'^assign_actor/$', views.assign_actor, name='assign_actor'),
                       url(r'^(?P<movie_slug>[\w\-]+)/apply/$', views.send_notification, name='apply'),
                       url(r'^search/$', views.search, name='search'),
                       url(r'^user/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
                       url(r'^rate/$', views.rate, name='rate'),
                       url(r'^add_to_watchlist/$', views.add_to_watchlist, name='watchlist'),
                       )

movies/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from datetime import datetime


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    first_name = models.CharField(max_length=128, blank=True)
    last_name = models.CharField(max_length=128, blank=True)
    picture = models.ImageField(upload_to='profile_images', default='profile_images/default_user_picture.jpg')
    info = models.TextField(blank=True)
    type = models.CharField(max_length=128)
    watchlist = models.ManyToManyField('Movie', null=True, blank=True)

    def __unicode__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        try:
            existing = UserProfile.objects.get(user=self.user)
            self.type = existing.type
            self.id = existing.id
        except UserProfile.DoesNotExist:
            pass
        super(UserProfile, self).save(*args, **kwargs)


class Genre(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Genre, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Actor(models.Model):
    user = models.OneToOneField(UserProfile, null=True)
    name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128, default='')
    info = models.TextField(blank=True)
    link = models.URLField(blank=True)
    available = models.CharField(max_length=3, default='no')

    def get_rating(self):
        ratings = ActorRating.objects.filter(actor=self)

        ratings_sum = 0
        for r in ratings:
            ratings_sum += r.rating

        if len(ratings) != 0:
            rating = ratings_sum/len(ratings)
        else:
            rating = 0

        return rating

    def get_characters(self):
        return Character.objects.filter(actor__name=self.name)

    def get_movies(self):
        characters = self.get_characters()
        return Movie.objects.filter(characters=characters)

    def __unicode__(self):
        return self.name


class Producer(models.Model):
    user = models.OneToOneField(UserProfile, null=True)
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    info = models.TextField(blank=True)
    link = models.URLField(blank=True)

    def get_movies(self):
        return Movie.objects.filter(user=self)

    def save(self, *args, **kwargs):
        self.first_name = self.user.first_name
        self.last_name = self.user.last_name
        self.info = self.user.info
        super(Producer, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.user.user.username


class Character(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField()
    actor = models.ForeignKey(Actor, blank=True, null=True)

    @staticmethod
    def get_character_list():
        characters = []
        i = 1
        for character in Character.objects.all():
            characters += (i, character.name)
            i += 1
        return characters

    def __unicode__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=128)
    year = models.IntegerField(default=0)
    genres = models.ManyToManyField(Genre)
    characters = models.ManyToManyField(Character, blank=True)
    user = models.ForeignKey(Producer, null=True)
    picture = models.ImageField(upload_to='movie_images', default='movie_images/default_movie_picture.jpg')
    summary = models.TextField()
    date_added = models.DateTimeField()
    link = models.URLField(blank=True)
    rating = models.FloatField(default=0.0)
    slug = models.SlugField(unique=True, blank=True)

    def get_rating(self):
        ratings_list = {}
        ratings = MovieRating.objects.filter(movie=self)

        ratings_sum = 0
        ratings_no = 0
        for r in ratings:
            ratings_sum += r.rating
            ratings_no += 1

        if len(ratings) != 0:
            rating = ratings_sum/len(ratings)
        else:
            rating = 0

        ratings_list['rating'] = rating
        ratings_list['ratings_no'] = ratings_no

        return ratings_list

    def show_rating(self):
        return self.get_rating()['rating']

    def get_image(self):
        if self.picture:
            return self.picture.url
        else:
            return 'movie_images/default_movie_picture.jpg'

    def get_actors(self):
        actors = []
        for character in self.characters.all():
            actors += Actor.objects.filter(character__name=character)

        return actors

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.date_added = datetime.now()
        super(Movie, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title


class MovieRating(models.Model):
    movie = models.ForeignKey(Movie)
    user = models.ForeignKey(UserProfile)
    rating = models.FloatField()

    def __unicode__(self):
        return self.movie.title


class ActorRating(models.Model):
    actor = models.ForeignKey(Actor)
    user = models.ForeignKey(UserProfile)
    rating = models.FloatField()

    def __unicode__(self):
        return self.actor.name


class Notification(models.Model):
    sender = models.ForeignKey(Actor)
    receiver = models.ForeignKey(Producer)
    message = models.TextField()
    date = models.DateTimeField()
    movie = models.ForeignKey(Movie)

    def save(self, *args, **kwargs):
        self.date = datetime.now()
        super(Notification, self).save(*args, **kwargs)


class Comment(models.Model):
    comment = models.CharField(max_length=256)
    date = models.DateTimeField(null=True)
    user = models.ForeignKey(UserProfile)
    movie = models.ForeignKey(Movie)


class Review(models.Model):
    text = models.TextField()
    date = models.DateTimeField()
    user = models.ForeignKey(UserProfile)
    movie = models.ForeignKey(Movie)

movies/forms.py
from django import forms
from django.contrib.auth.models import User
from movies.models import Movie, Actor, Character, Genre, Comment, UserProfile, Notification


class MovieForm(forms.ModelForm):

    character_list = [(c.id, c.name) for c in Character.objects.all()]

    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="Title: ")
    year = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="Year: ")

    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        help_text="Genres: ",

    )

    summary = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'cols': '50'}), help_text='Summary: ')
    link = forms.URLField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text='Link: ', required=False)
    picture = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), help_text='Picture: ', required=False)

    class Meta:

        model = Movie
        fields = ('title', 'year', 'genres', 'summary', 'link', 'picture',)


class CharacterForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="Name: ")
    desc = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'cols': '50'}),
                           help_text='Description: ', required=False)

    class Meta:

        model = Character
        fields = ('name', 'desc', )


class CommentForm(forms.ModelForm):

    comment = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Comment
        fields = ('comment', )


class UserProfileForm(forms.ModelForm):

    USER_TYPES = [(1, 'Member'), (2, 'Actor'), (3, 'Producer')]

    type = forms.ChoiceField(
        choices=USER_TYPES,
        help_text="Type: ",
        required=False
    )
    first_name = forms.CharField(max_length=128, help_text='First Name: ', required=False)
    last_name = forms.CharField(max_length=128, help_text='Last Name: ', required=False)

    class Meta:
        model = UserProfile
        fields = ('type', 'first_name', 'last_name', 'picture', 'info')


class NotificationForm(forms.ModelForm):

    message = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Notification
        fields = ('message', )

templates/movies/actor.html
{% extends 'movies/base.html' %}

{% block title %}{{ actor.name }}{% endblock %}

{% block body_block %}
    <h1>{{ actor.name }}</h1>

    <h3>Rating: {{ rating }} / 5.0</h3>

    <h3>Movies</h3>
    <ul>
        {% for movie in movies %}
            <li><a href="{% url 'movie' movie.slug %}">{{ movie }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

templates/movies/actors.html
{% extends 'movies/base.html' %}

{% block title %}Movies - Homepage{% endblock %}

{% block body_block %}
    <div class="movie movie-first-box">
        <h3 class="movie-header">Actors</h3>
        <ul class="movie-list">
            {% if actors %}
                {% for actor in actors %}
                    <li><a href="{% url 'profile' actor.user.user.username %}">{{ actor.name }} {{ actor.last_name }}</a></li>
                {% endfor %}
            {% else %}
                No actors present yet.
            {% endif %}

        </ul>
    </div>

    <div class="movie">
        <h3 class="movie-header">Producers</h3>
        <ul class="movie-list">
            {% if producers %}
                {% for producer in producers %}
                    <li><a href="{% url 'profile' producer.user.user.username %}">{{ producer.first_name }} {{ producer.last_name }}</a></li>
                {% endfor %}
            {% else %}
                No actors present yet.
            {% endif %}

        </ul>
    </div>


{% endblock %}

{% block sidebar %}
    <div class="panel panel-primary">
        <div class="panel-heading">Available actors</div>

        <ul class="list-group">
            {% for actor in available_actors %}
                <li class="list-group-item"><a href="{% url 'profile' actor.user.user.username %}">{{ actor.name }} {{ actor.last_name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/movies/add_actor.html
{% extends 'movies/base.html' %}

{% block body_block %}


        <div class="col-lg-offset-2">
            <h2 class="form-signin-heading">Step 3: Assign actors to characters</h2>
        </div>

        {% if movie %}
            <div class="form-group" >
                <div class="col-lg-offset-2 col-sm-9 col-xs-12 col-lg-9">
                    <ul style="padding: 0;">
                    {% for character, actor in character_actor.items  %}
                        {% if actor %}
                            <li class="col-lg-12" style="padding: 0; margin: 5px 0;">
                                <label class="col-lg-5 control-label">
                                    {{ character.name }}:
                                </label>
                                <div class="col-lg-7">
                                    <a href="{% url 'profile' character.actor.user.user.username %}" >{{ actor.name }}</a>
                                </div>
                            </li>

                        {% else %}
                            <li class="col-lg-12" style="padding: 0; margin: 5px 0;">
                                <label class="col-lg-5 control-label" >
                                    {{ character.name }}:
                                </label>
                                <div id="d{{ character.id }}" class="col-lg-7">
                                    <div class="input-group">
                                        <select id="s{{ character.id }}" class="form-control" name="type" >
                                            {% for value, name in actor_options.items %}
                                                <option value="{{ value }}">{{ name }}</option>
                                            {% endfor %}
                                        </select>
                                          <span class="input-group-btn">
                                            <button data-characterid="{{ character.id }}" data-movieid="{{ movie.id }}" class="assign btn btn-default" type="button">Add</button>
                                          </span>
                                    </div><!-- /input-group -->
                                </div><!-- /.col-lg-6 -->
                            </li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}

        <div class="col-lg-offset-2">
            <a class="btn btn-primary" href="{% url 'profile' user.username %}">Finish</a>

        </div>






{% endblock %}

templates/movies/add_character.html
{% extends 'movies/base.html' %}

{% block body_block %}

	<form class="form-horizontal" id="character_form" method="post" action="{% url 'add_character' movie.slug %}">
        <div class="col-lg-offset-2">
            <h2 class="form-signin-heading">Step 2: Add characters to your film</h2>
        </div>

        {% if movie %}
            <div class="form-group" >
                <label class="col-lg-2 control-label">Existing characters: </label>
                <div class="col-sm-9 col-xs-12 col-lg-9">
                    <ul style="padding: 0;">
                    {% for character, actor in character_actor.items  %}
                        {% if actor %}

                            <li>{{ character.name }} - <a href="{% url 'profile' character.actor.user.user.username %}" >{{ actor.name }}</a></li>
                        {% else %}
                            <li>{{ character.name }}</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group" >
                <label class="col-lg-2 control-label">{{ field.help_text }} </label>
                <div class="col-sm-9 col-xs-12 col-lg-9">
                    {{ field.errors }}
                    {{ field }}
                </div>
            </div>
        {% endfor %}

        <div class="col-lg-offset-2">
            <button type="submit" class="btn btn-primary" name="submit">Add</button>

            <a style="float:right; margin-right: 55px; " class="btn btn-primary" href="{% url 'add_actor' movie.slug %}">Next Step</a>
            <a style="float:right; " class="btn btn-primary" href="{% url 'add_movie' %}">Previous Step</a>

        </div>



    </form>

{% endblock %}

templates/movies/add_movie.html
{% extends 'movies/base.html' %}

{% block body_block %}

    <style>
        ul {
            padding: 0;
        }
    </style>

	<form class="form-horizontal" id="category_form" method="post" action="{% url 'add_movie' %}" enctype="multipart/form-data">

        <div class="col-lg-offset-2">
            <h2 class="form-signin-heading">Add a new film</h2>
        </div>

        {% csrf_token %}
        {% for hidden in movie_form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in movie_form.visible_fields %}
            <div class="form-group" >
                <label class="col-lg-2 control-label">{{ field.help_text }} </label>
                <div class="col-sm-9 col-xs-12 col-lg-9">
                    {{ field.errors }}
                    {{ field }}
                </div>
            </div>
        {% endfor %}

        <div class="col-lg-offset-2">
            <button type="submit" class="btn btn-primary" name="submit">Submit</button>
        </div>



    </form>

{% endblock %}

templates/movies/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static 'stylesheets/offcanvas.css' %}" rel="stylesheet">
    <link href="{% static 'stylesheets/base.css' %}" rel="stylesheet">
    <link href="{% static 'stylesheets/movie.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/jRating.jquery.css' %}" media="screen" />


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>{% block title %}Movies{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-static-top navbar-inverse">
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right" >
            <div class="col-xs-12 col-sm-9 col-lg-10 col-md-10 col-lg-offset-1" >

                <!-- Logo -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand active" href="{% url 'index' %}">FilmBook</a>
                </div>


                <!-- Search form -->
                <div class="search-wrapper col-lg-8 col-md-8 col-sm-10 col-xs-12">
                    <form class="navbar-form navbar-left" role="search" method="post" action="{% url 'search' %}">
                        {% csrf_token %}
                        <div class="input-group input-group-sm">
                            <input type="text" name="search_textbox" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn"><button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button></span>
                        </div>
                    </form>
                </div>

                <!-- Main links -->
                <div id="navbar" class="collapse navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">

                        <li><a href="{% url 'genres' %}">Films</a></li>
                        <li><a href="{% url 'actors' %}">People</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span>
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                    {% if user.is_authenticated %}
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'profile' user.username%}">Profile</a></li>
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'auth_logout' %}?next=/movies/">Logout</a></li>

                                    {% else %}
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'registration_register' %}">Register Here</a></li>
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'auth_login' %}">Login</a></li>
                                    {% endif %}
                                </ul>

                        </li>
                    </ul>

                </div>
            </div><!-- end row-->

        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->



<div class="container">

    <div class="row row-offcanvas row-offcanvas-right">

            <div class="content col-xs-12 col-sm-7 col-lg-7 col-md-7 col-lg-offset-1 col-md-offset-1">


                {% block body_block %}{% endblock %}



            </div>

            <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 sidebar-offcanvas" id="sidebar">
                {% block sidebar %}{% endblock %}
            </div><!--/.sidebar-offcanvas-->




    </div><!--/row-->

</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

<script src="offcanvas.js"></script>

<script type="text/javascript" src={% static 'js/jRating.jquery.js' %}></script>
<script type="text/javascript" src={% static 'js/movieRating.js' %}></script>
<script type="text/javascript" src={% static 'js/addToWatchlist.js' %}></script>
<script type="text/javascript" src={% static 'js/assignActor.js' %}></script>




</body>
</html>

templates/movies/edit_movie.html
{% extends 'movies/base.html' %}

{% block body_block %}

    <style>
        ul {
            padding: 0;
        }
    </style>

	<form class="form-horizontal" id="category_form" method="post" action="{% url 'add_movie' %}" enctype="multipart/form-data">

        <div class="col-lg-offset-2">
            <h2 class="form-signin-heading">Edit your movie</h2>
        </div>

        {% csrf_token %}
        {% for hidden in movie_form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in movie_form.visible_fields %}
            <div class="form-group" >
                <label class="col-lg-2 control-label">{{ field.help_text }} </label>
                <div class="col-sm-9 col-xs-12 col-lg-9">
                    {{ field.errors }}
                    {{ field }}
                </div>
            </div>
        {% endfor %}

        <div class="col-lg-offset-2">

            <a class="btn btn-primary" href="{% url 'add_character' movie.slug %}">Edit characters</a><br />
            <a class="btn btn-primary" href="{% url 'add_actor' movie.slug %}">Edit actors</a>
        </div>

    </form>




{% endblock %}

templates/movies/edit_profile.html
{% extends 'movies/base.html' %}

{% block body_block %}

	<form class="form-horizontal" id="category_form" method="post" action="{% url 'edit_profile' user.username %}" enctype="multipart/form-data">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="col-lg-offset-2">
            <h2 class="form-signin-heading">Edit your profile</h2>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_firstname">First name:</label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <input class="form-control" id="id_firstname" type="text" name="first_name" value="{{ user_profile.first_name }}" />
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_lastname">Last name:</label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <input class="form-control" id="id_lastname" type="text" name="last_name" value="{{ user_profile.last_name }}" />
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_info">About me:</label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <textarea class="form-control" rows="6" id="id_info" name="info" >{{ user_profile.info }}</textarea>
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_picture">Picture:</label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <input class="form-control" id="id_picture" type="file" name="picture" accept="image/*" />
            </div>
        </div>

        <div class="col-lg-offset-2">
            <button type="submit" class="btn btn-default">Save</button>
        </div>






    </form>

{% endblock %}

{% block sidebar %}
    {% if user == user_profile.user %}
        {% if movies_produced %}
            <div class="panel panel-primary">
                <div class="panel-heading">My films</div>

                <div class="list-group">
                    {% for movie in movies_produced %}
                        <a class="list-group-item" href="{% url 'movie' movie.slug %}">{{ movie }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if movies_played_in %}
            <div class="panel panel-primary">
                <div class="panel-heading">Films I played in</div>

                <div class="list-group">
                    {% for movie in movies_played_in %}
                        <a class="list-group-item" href="{% url 'movie' movie.slug %}">{{ movie }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="panel panel-primary">
            <div class="panel-heading">My Watchlist</div>

            <div class="list-group">
                {% for movie in watchlist %}
                    <a class="list-group-item" href="{% url 'movie' movie.slug %}">{{ movie }} </a>
                {% endfor %}
            </div>
        </div>




    {% endif %}


{% endblock %}

templates/movies/user_profile_form.html
{% extends 'movies/base.html' %}

{% block body_block %}

	<form class="form-horizontal" id="category_form" method="post" action="{% url 'user_profile_details' user.username %}" enctype="multipart/form-data">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="col-lg-offset-2">
            <h2 class="form-signin-heading">Fill in your details</h2>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_type">Type: </label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <select class="form-control" id="id_type" name="type" >
                    {% for value, name in types.items %}
                        <option value="{{ value }}">{{ name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_firstname">First name: </label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <input class="form-control" id="id_firstname" type="text" name="first_name" value="{{ user_profile.first_name }}" />
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_lastname">Last name: </label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <input class="form-control" id="id_lastname" type="text" name="last_name" value="{{ user_profile.last_name }}" />
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_info">About me: </label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <textarea class="form-control" rows="6" id="id_info" name="info" >{{ user_profile.info }}</textarea>
            </div>
        </div>

        <div class="form-group" >
            <label class="col-lg-2 control-label" for="id_picture">Picture: </label>
            <div class="col-sm-9 col-xs-12 col-lg-9">
                <input class="form-control" id="id_picture" type="file" name="picture" accept="image/*" />
            </div>
        </div>

        <div class="col-lg-offset-2">
            <button type="submit" class="btn btn-default">Save</button>
        </div>







    </form>

{% endblock %}